language: node_js
node_js:
  - "8"
  - "7"
  - "6"
cache: yarn
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test -- --coverage
after_script: greenkeeper-lockfile-upload
after_success:
  - bash <(curl -s https://codecov.io/bash)
