language: node_js
node_js:
  - "7"
cache: yarn
script:
  - yarn lint
  - yarn test -- --coverage
branches:
  only:
    - master
notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
